### ISSUE TITLE
Digital Appendix

### ISSUE THREAD

**Issue by jasonltorchinsky** [AlexandraLJones/MCBRaT3D#4]
There are several mentions in the accompanying dissertation of a "digital appendix". Would this digital appendix be this GitHub repository, or is it some other archive?

**Comment by AlexandraLJones** [comment]
Yeah, I noticed that too. And I was trying to find it when answering your last question. My fuzzy recollection is that the University of Illinois offered a digital appendix option that code could be uploaded to. But I don't see it connected to the dissertation anymore. It may be lost. But if I think about what would have been placed in that appendix, it's probably the code that is available in github, just frozen in that moment of time. There were definitely improvements made to the code base after my dissertation was submitted. But we may have lost some of these namelists, input files, scripts, etc.

**Comment by jasonltorchinsky** [comment]
Thanks for the response! From what I've seen in the dissertation, it did contain several namelists that may have been of use. We're still making progress, though!
